version: '3'     # Composeファイルの書式のバージョン
services:    # サービスを定義する項目
  app:
    build:
      context: app
      dockerfile: Dockerfile
    # image: python:3.7
    container_name: app-server
    hostname: app-server
    # tty: trueと記述すると、docker-compose up でコンテナを起動させた際に、
    #      コンテナがすぐに終了してしまうのを防ぐことができます。
    tty: true
    working_dir: /var/www/
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /var/www/
      TZ: Asia/Tokyo
    volumes:
      - ./app/:/var/www/
    ports:
      - 5000:5000
      # - 3031:3031
      # - 3031:5000