version: '3'     # Composeファイルの書式のバージョン
services:    # サービスを定義する項目
  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    # image: python:3.7
    container_name: web_flask
    # tty: trueと記述すると、docker-compose up でコンテナを起動させた際に、
    #      コンテナがすぐに終了してしまうのを防ぐことができます。
    tty: true
    working_dir: /usr/script/flask
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /usr/script/flask/
    volumes:
      - ./:/usr/script/flask/
    ports:
       - 5000:5000
    #  - 8000:8000    # 開けなくてもいけるかも？
    # networks:
    #   - my-network